version: "3.9"
services:
  tracker:
    container_name: tracker
    image: tracker:latest
    depends_on: 
      - db
      - redis
    restart: always
    network_mode: bridge
    environment:       
      - DB_NAME=tracker
      - DB_USER=tracker
      - DB_PWD=tracker
      - DB_ADDR=postgres
      - DB_PORT=5432
      - REDIS_ADDR=redis:6379
  redis:
    image: redis:6.0.10-alpine3.12
    restart: always
    network_mode: bridge
  db:
    container_name: postgres
    image: postgres:13.1
    restart: always
    network_mode: bridge
    environment: 
      - POSTGRES_DB=tracker
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=tracker
    ports: 
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
